### ISSUE TITLE
Kann Termine nicht speichern.

### ISSUE THREAD

**Issue by Pixeldaniel** [FriendsOfREDAXO/forcal#12]
Wenn ich über das Termine-Tab versuche einen neuen Termin einzutragen, kann ich diesen nicht speichern. 
Es kommt die leider wenig hilfreiche Fehlermeldung "Fehler beim Speichern!"
Wenn ich vom Kalender her komme funktioniert alles einwandfrei. 

Mein erster Gedanke war, dass es in einer Form mit den verschiedenen GET-Parametern zusammen hängt.
Von der Termineseite: "/redaxo/index.php?page=forcal/entries&func=add&list=e175387d"
Vom Kalender aus: ".../redaxo/index.php?page=forcal/entries&func=add&itemdate=2021-10-13"
Ohne den itemdate-Parameter scheint etwas zu fehlen.

Dafür kommt, wenn man vom Kalender kommt, keine Bestätigung, dass die Eingaben gespeichert wurden.

**Comment by skerbis** [comment]
ich schätze dass hier was serverseitig blockiert. Mod secur oder so? - Ich schließe erstmal, da sonst niemand was gemeldet hat.
