### ISSUE TITLE
Kalender Front End

### ISSUE THREAD

**Issue by DevTheJul** [FriendsOfREDAXO/forcal#19]
Hey erstmals :)

ich wollte fragen ob ihr eine Idee habt warum der Kalender bei mir in der Bearbeitungsansicht so aussieht:
![image](https://user-images.githubusercontent.com/69975747/154999027-d042ccb8-2970-4e8b-89bf-093e584f934c.png)

jedoch in der "echten Ansicht" nichts vorhanden ist, da ist einfach nichts.

Ich würde mich voll freuen wenn mir jemand bitte helfen kann.

Vielen Dank und Liebe Grüße

Julian

**Comment by skerbis** [comment]
Was meinst du mit echter Ansicht?

**Comment by DevTheJul** [comment]
> Was meinst du mit echter Ansicht?

Die Front End Ansicht^^

**Comment by skerbis** [comment]
welches Modul? Bitte gerne auch auf slack fragen

**Comment by DevTheJul** [comment]
> welches Modul? Bitte gerne auch auf slack fragen

kenn mich mit slack leider nd so aus xD

habe n PHP Modul umgebaut:

`<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/core/main.min.css') ?>">
<link rel="stylesheet" href="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/daygrid/main.min.css') ?>"> 
<link rel="stylesheet" href="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/list/main.min.css') ?>">
<link rel="stylesheet" href="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/timegrid/main.min.css') ?>">

<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/core/main.js') ?>"></script>
<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/daygrid/main.js') ?>"></script>   
<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/interaction/main.js') ?>"></script>   
<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/timegrid/main.js') ?>"></script>    
<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/list/main.js') ?>"></script> 
<script type="text/javascript" src="<?= rex_url::base('assets/addons/forcal/vendor/fullcalendar/packages/core/locales-all.min.js') ?>"></script>
<script type="text/javascript" src="<?= rex_url::base('assets/js/forcal.js') ?>"></script>
</head>
<body>
</body>
</html>


<?php
// Ausgabe der Detail-Seite
if(!is_null(rex_request::get('event_id', 'integer', null))) {
    $data = \forCal\Handler\forCalHandler::exchangeEntry(rex_request::get('event_id'), false);
    // dump($data);
    $header = '<div class="forcal-title">';
    $header .= '<h1>'.$data['title'].'</h1>';
    $header .= '<span class="forcal-meta">' . \forCal\Utils\forCalDateTimeHelper::getFromToDate(new \DateTime($data['start']), new \DateTime($data['end'])) . ' ' . \forCal\Utils\forCalDateTimeHelper::getFromToTime(new \DateTime($data['start']), new \DateTime($data['end'])) . '</span> ';
    $header .= '<hr style="border-color:'.$data['color'].'"> ';
    // Backlink
    $header .= '<div class="pull-left">
    <a class="btn btn-primary" href="'.rex_getUrl('REX_ARTICLE_ID', rex_clang::getCurrentId()).'">Kalender</a>
    </div>';
    // Bild
    if (!empty($data['entries_image'])) {
        $media = rex_media::get($data['entries_image']);
        $header .= '<img class="forcal-img" src="'.$media->getUrl().'">';
    }
    $header .= '</div>';
    $teaser = '<div class="forcal-teaser">'.$data['teaser'].'</div>';
    echo $header.$teaser.'<article class="forcal-text">'.$data['text'].'</article>';
} 
// Kalender ausgeben
else {
?>
<div id="forcal" class="forcal" data-link="<?php echo rex_getUrl('REX_ARTICLE_ID', rex_clang::getCurrentId());?>"></div>
<?php } ?>
`

**Comment by skerbis** [comment]
jQuery scheint zu fehlen

**Comment by DevTheJul** [comment]
![image](https://user-images.githubusercontent.com/69975747/155023565-b07e3a84-e7b2-4ac5-bc80-79794261f1f0.png)
Habe es eigentlich drinnen :/

**Comment by skerbis** [comment]
ich kann jQuery in deinem code nicht entdecken

**Comment by skerbis** [comment]
bide das bitte vor allen Skripten ein

```js
<script   src="https://code.jquery.com/jquery-3.6.0.js"   integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="   crossorigin="anonymous"></script>
```

**Comment by DevTheJul** [comment]
Es funktioniert vielen Dank! 😉

**Comment by DevTheJul** [comment]
Jetzt zeigt er mir aber nur mehr den Kalender ohne Events an :/

**Comment by skerbis** [comment]
forcal.js hast du erstellt?

**Comment by DevTheJul** [comment]
> 
yep

**Comment by DevTheJul** [comment]
das aus der Vorlage
