### ISSUE TITLE
Kalender zeigt nichts an

### ISSUE THREAD

**Issue by DevTheJul** [FriendsOfREDAXO/forcal#21]
Hey,

entschuldige bitte nochmal die Störung, aber kann mir bitte jemand helfen - mein Kalender zeigt keine Events an :/

LG Julian

**Comment by DevTheJul** [comment]
PS: habe leider kein Slack und kenne mich da nicht aus sry :c

**Comment by skerbis** [comment]
@DevTheJul schau mal https://www.redaxo.org/support/community/#slack , es ist wirklich sehr einfach  - würde mich freuen und dir dort gerne helfen
