### ISSUE TITLE
entry_name enthält auch die Kategorie

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/forcal#23]
Nach allem, was ich bisher rausgefunden und ausprobiert habe, ist es nicht möglich, den reinen Titel auszugeben. 
`$event->entry_name` gibt immer das format `"Veranstaltungstitel - Kategoriename"` aus. Auch via dump($events) kann ich nicht den reinen Titel finden.

**Comment by skerbis** [comment]
kann ich nicht bestätigen

**Comment by cukabeka** [comment]
Danke fürs Testen - ich habe jetzt den Grund gefunden: 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/688274/181022078-80767f39-1b42-453e-9af3-38a126bcd1c7.png">
Diese Einstellung ist etwas unglücklich formuliert, finde ich. Sobald hier "name" eingtragen ist, wird der Kategoriename in den entry_name gehängt. 
Aber insofern kein Bug. 
Als Text vielleicht "Als Identifikation der Kategorie zusätzlich im Veranstaltungstitel mit ausgeben"?

**Comment by skerbis** [comment]
Ich kann es nicht reproduzieren. Wo genau findet das statt? 
Wie lautet deine Modulausgabe?

**Comment by cukabeka** [comment]
Also, der Modulcode ist (snippet) 

```
if ($venues == '') {
    $entries = \forCal\Handler\forCalHandler::getEntries($start, $filter_date, true, 'SORT_ASC', $categoryId);
}
if ($venues != '') {
    $entries = \forCal\Handler\forCalHandler::getEntries($start, $filter_date, true, 'SORT_ASC', $categoryId, $venues);
}

    foreach ($entries as $data) {
        $event                 = $data['entry'];
        echo '<strong>' . $event->entry_name . '</strong>;
   }
```

Wenn ich jetzt in den FORCal Einstellungen "name" bei der Option hier auswähle:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/688274/181114034-01549b46-ff41-4765-aba0-fc2522507bbc.png">
Dann bekomme ich für `$event->entry_name` statt "Veranstaltungsname" die Ausgabe "Veranstaltungsname - Kategoriename".

**Comment by skerbis** [comment]
Eigentlich ist es nur für das backend gedacht. Bei mir passiert es nicht, ich check das aber

**Comment by cukabeka** [comment]
Kurzer Nachtrag hierzu: Es gibt ein Flag in den Einstellungen, mit dem man das einschalten kann. In dem Fall wird der Name und die Kategorie statt nur des Namens ausgegeben. Das hatte ich übersehen. Vielleicht ein bisschen irreführend.

**Comment by cukabeka** [comment]
Danke fürs chechen!

**Comment by skerbis** [comment]
ist im aktuellen Github Stand gefixt (Release folgt). Nur auf den Forcal-Seiten im Backend wird es nun angezeigt. Es ist ja "nur" eine Hilfe für die Redakteuri:innen
