### ISSUE TITLE
Defaultwert für Uhrzeiten (ganztägiges Ereignis)

### ISSUE THREAD

**Issue by chrisrex** [FriendsOfREDAXO/forcal#25]
Schön wäre die Möglichkeit jeweils einen default-Wert für die Uhrzeiten (ganztägiges Ereignis), damit das Modul für die Detailausgabe besser funktioniert. (FullCalendar im Frontend)

**Comment by skerbis** [comment]
Besser wäre wenn bei ganztägigen Ereignissen keine Uhrzeit gespeichert wird.

**Comment by skerbis** [comment]
https://github.com/redaxo/redaxo/pull/5520#pullrequestreview-1249832679
