### ISSUE TITLE
SQL-Fehler bei Eingabe von "falschem Datum"

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/forcal#27]
**Description / Beschreibung**
Gibt man ein Datum eines Termins manuell in das Feld ein und vertauscht Monat und Tag zB 2022-28-10 erhält man einen SQL Fehler. Die falsche Eingabe sollte vor dem Speichern abgefangen werden.

DateTime::__construct(): Failed to parse time string (2022-28-10 16:00:00) at position 6 (8): Unexpected character

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by skerbis** [comment]
Die Felder müssten als date Felder deklariert werden. Leider gibt's da noch n CSS-Problem im REDAXO Core.
