### ISSUE TITLE
eigene felder/custom entries: attribute beim typ 'media' ermöglichen

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/forcal#3]
während z.b. das der feldtyp 'textarea' mit eigenen attributen ausgestattet werden kann, funktioniert das beim typ 'media' nicht.
das wäre hilfreich um parameter wie 'preview' oder 'types' zu übermitteln.

weiterhin wäre es sehr schön hier auch den typ 'imagelist' zur verfügung zu haben.

**Comment by skerbis** [comment]
wird nicht realisiert
