### ISSUE TITLE
Update auf Grund Abhängigkeiten nicht möglich

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/forcal#31]
Beim Versuch auf die neueste Version zu updaten wird ein Fehler geworfen:
```
AddOn forcal konnte aus folgendem Grund nicht aktualisiert werden:
Es kann nicht gemeinsam mit dem AddOn quick_navigation mit der Versionsbedingung <6.0.0 aktiviert sein!
```

Problem dabei ist, dass parallel Quick-Navigation dies bringt:
```
AddOn quick_navigation konnte aus folgendem Grund nicht aktualisiert werden:
Es kann nicht gemeinsam mit dem AddOn forcal mit der Versionsbedingung <3.7.0 aktiviert sein!
```

**Comment by skerbis** [comment]
Ja ist doof. Weiß nicht wie ich das am besten lösen kann. 
Forcal bitte einmal deaktivieren, Quicknavi aktualisieren, dann Forcal aktualisieren und wieder aktivieren.

**Comment by iceman-fx** [comment]
Kannst Du diese Prüfung nicht direkt im PHP-Code machen, um dann die entsprechende Funktion zu nutzen?

**Comment by skerbis** [comment]
- wird nicht weiter verfolgt -
