### ISSUE TITLE
Sonderzeichen im Titel nach Duplizieren werden falsch dargestellt

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/forcal#33]
In der aktuellen Version werden Hochkommas in den Titel eingefügt, welche im Eingabefeld falsch dargestellt werden.

![1](https://user-images.githubusercontent.com/4291047/204304218-b0d64cc9-862d-4ff4-8ffd-7ffc69c323bc.PNG)

**Comment by iceman-fx** [comment]
Die Zeichen sind nicht von mir.
Die werden beim duplizieren autom. Vom Kalender eingefügt.

**Comment by iceman-fx** [comment]
Das hat mit dem alten Issue nix zu tun.
Da wurden von mir eingefügte Sonderzeichen falsch übernommen.

**Comment by skerbis** [comment]
@iceman-fx  bitte den aktuellen Github-Stand testen

**Comment by iceman-fx** [comment]
Schaut gut aus. Klappt.

**Comment by skerbis** [comment]
Ich hoffe es hat keine Side-Effekte. Melde Dich sollte es dadurch zu Problemen kommen. Gerne auch in Slack.
