### ISSUE TITLE
Suchfunktion innerhalb der Terminübersicht (Backend)

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/forcal#34]
Wenn man viele Termine hat, wäre eine einfache Suchfunktion (Suchbegriff) innerhalb der Terminübersicht hilfreich.
Gern auch mit zusärtzlicher Option zur Einschränkung nach Kategorie.

**Comment by skerbis** [comment]
Installiere Watson. Die Suche ist in Watson integriert.

**Comment by skerbis** [comment]
Die Watson-Suche ist aber schneller und besser.

**Comment by skerbis** [comment]
Da andere Entscheidungen getroffen wurden, schließe ich an dieser Stelle.
