### ISSUE TITLE
Zeitauswahl ist englisch ohne Angabe von PM oder AM - besser 24h Darstellung (Backend)

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/forcal#35]
![ScreenHunter 302](https://user-images.githubusercontent.com/4291047/206457552-e361fbeb-e4e5-4ba8-b87a-58fc68e35098.png)

Es wäre besser, wenn die Zeitauswahl ein deutsches Format (bzw. je nach Backendsprache) darstellen würde.
Im Beispiel hier müsste es 14:14:16 sein.

**Comment by skerbis** [comment]
Sicher?

![Bildschirm­foto 2022-12-08 um 15 03 01](https://user-images.githubusercontent.com/791247/206465661-f89e15de-cf5d-4fca-8fed-be9a196ea4fa.png)

**Comment by iceman-fx** [comment]
Ja. Siehe mein screenshot oben.
Scheint aber nur das inputfeld zu betreffen.

**Comment by iceman-fx** [comment]
Habe es gerade nochmal gecheckt.

Bei einem neuen termin wird aktuell 4h anstatt 16h vorausgewählt.

**Comment by skerbis** [comment]
@iceman-fx bitte aktuellen Github-Stand testen

**Comment by skerbis** [comment]
Released
