### ISSUE TITLE
Mehr als 1 Kategorie zuweisbar

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/forcal#36]
Es wäre toll, wenn man mehr als 1 Kategorie einem Termin zuweisen könnte.

**Comment by skerbis** [comment]
Die Kategorien verhalten sich wie in den meisten Kalenderservern wie einzelne Kalender. 
Du kannst aber mit den Customfields eigene Zuordnungen / Relationen erzeugen.
