### ISSUE TITLE
Sortierung der Calendar-Entries innerhalb eines Datums z.B. nach Titel ermöglichen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/forcal#6]
Momentan ist es so, dass einzelne Einträge, die am selben Datum stattfinden z.B. per 
`\forCal\Handler\forCalHandler::getEntries($start, $filter_date, true, 'SORT_ASC', $categoryId);` korrekt nach dem Datum sortiert werden.
Hat man nun aber 3 Einträge z.B. am 01.01.2022 werden diese dann anschließend  (glaube ich, ich habe nicht nachgesehen) nach id sortiert.

Hier wäre es wünschenswert, dass man noch eine weitere Sortierung zB nach Titel (name_1) vornehmen könnte.

Momentan:

- 01.01.2022 - Frohes neues Jahr _{id:1}_
- 01.01.2022 - Xmas ist vorbei _{id:2}_
- 01.01.2022 - Alles Gute zum neuen Jahr _{id:3}_

Gewünscht zB:

- 01.01.2022 - Alles Gute zum neuen Jahr _{id:3}_
- 01.01.2022 - Frohes neues Jahr _{id:1}_
- 01.01.2022 - Xmas ist vorbei _{id:2}_

Mit folgendem Code habe ich es entsprechend sortiert bekommen:
```
 $entries = \forCal\Handler\forCalHandler::getEntries($start, $filter_date, true, 'SORT_ASC', $categoryId);
// Sortierung damit innerhalb gleicher Tage noch der Titel nach alphabet sortiert wird
    usort($entries, function($a, $b) {
        /*
         When the $a value is on the left of the spaceship operator and the $b value is on the right, ASCending sorting is used.
         When the $b value is on the left of the spaceship operator and the $a value is on the right, DESCending sorting is used.
         * */
        return
            [$a['entry']->entry_start_date, $a['entry']->entry_name]
            <=>
            [$b['entry']->entry_start_date, $b['entry']->entry_name];
    });
```
https://stackoverflow.com/a/54647220

Evtl. könnte man hier andenken die Sortierung nach dem Datum  noch nach mehreren Gesichtspunkten vorzunehmen (Titel, Venue, Kategorie).

**Comment by skerbis** [comment]
Wünschenswert aus meiner Sicht wäre die Sortierung: 

Datum -> Uhrzeit -> Name

**Comment by skerbis** [comment]
@danspringer https://github.com/FriendsOfREDAXO/forcal/blob/f8d148378364b9b72466d38e8f119cc3e50feb7d/lib/forcal/Handler/forcalHandler.php#L494

Hier einen EP anlegen?
